/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 comp.gltf --transform
Author: assetfactory (https://sketchfab.com/assetfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-game-ready-53e7eeb0f69540d2892ad6aa5f47bd39
Title: Sci - fi computer game ready
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/comp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002_digital_displays_0.geometry} material={materials.digital_displays} position={[0, 0.289, 3.122]} rotation={[-1.469, 0, 0]} />
      <mesh geometry={nodes.Plane002_digital_display_sides_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.289, 3.122]} rotation={[-1.469, 0, 0]} />
      <mesh geometry={nodes.Circle_metal_2_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.948]} rotation={[0, Math.PI / 2, 0]} scale={1.238} />
    </group>
  )
}

useGLTF.preload('/comp-transformed.glb')
